### ISSUE TITLE
00-Lab enhancement

### ISSUE THREAD

**Issue by mwvoss** [uiowa-mri-course-2018/Labs#6]
Add narrative for rationale of jupyter notebooks, short exercises to practice coding within notebook, and exercise to practice working with github.  These would likely be worked on interactively on 1/29 (Technical landscape of MRI processing )

**Comment by jdkent** [comment]
Starting to cover this will #7, it is a WIP.

**Comment by jdkent** [comment]
Going to close this issue for now. Re-open if there's more discussion.
